---
title: "Fig3&4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fig 3B 
```{r}
library(ggplot2)
setwd("/lustre/user/liclab/pengt/projects/nucleus/new/NAIR")
df = read.table('./actd/trans_interaction',header = T,sep = '\t')
ggplot(df,aes(x=group,y=trans)) +geom_boxplot(aes(fill = group),width=0.6)+
  scale_fill_manual(values = c("#2BA809", "#F97164"))+theme_bw() +ylim(0,30)+
  theme(axis.line = element_line(size=1, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank(),
        axis.text.x=element_text(colour="black", size = 9),
        axis.text.y=element_text(colour="black", size = 9))+xlab("")+ylab("Trans interaction (%)")
```

## Fig 3D 
```{r}
setwd("/lustre/user/liclab/pengt/projects/nucleus/new/NAIR")
df = read.table('./actd/compartment_score',header = T)
df$variable = factor(df$variable,levels = c('Ctrl','ActD'))
library(ggplot2)
ggplot(df, aes(variable, value))+ 
  geom_boxplot(width = 0.4,  notchwidth = .6, outlier.shape = NA,aes(fill=variable)) +
  labs(x=NULL,y="Log2 ((AA*BB)/(AB2))") +
  theme_classic() +
  theme(text = element_text(size = 20),legend.position = "none") +ylim(2,3.5)+
  scale_fill_manual(values=c("#2BA809", "#F97164"))
```

## Fig 3F and 5B
```{r}
setwd('/lustre/user/liclab/pengt/projects/nucleus/new/NAIR/actd/')
bb_actd = read.table('./BB_interaction_actd')
ab_actd = read.table('./AB_interaction_actd')
aa_actd = read.table('./AA_interaction_actd')
bb = read.table('../BB_interaction')
ab = read.table('../AB_interaction')
aa = read.table('../AA_interaction')
aa_cis_num = sum(aa[aa$V1==aa$V4,7])/287704860*200000000
aa_trans_num = sum(aa[aa$V1!=aa$V4,7])/287704860*200000000
ab_cis_num = sum(ab[ab$V1==ab$V4,7])/287704860*200000000
ab_trans_num = sum(ab[ab$V1!=ab$V4,7])/287704860*200000000
bb_cis_num = sum(bb[bb$V1==bb$V4,7])/287704860*200000000
bb_trans_num = sum(bb[bb$V1!=bb$V4,7])/287704860*200000000

aa_cis_num_actd = sum(aa_actd[aa_actd$V1==aa_actd$V4,7])/162823588*200000000
aa_trans_num_actd = sum(aa_actd[aa_actd$V1!=aa_actd$V4,7])/162823588*200000000
ab_cis_num_actd = sum(ab_actd[ab_actd$V1==ab_actd$V4,7])/162823588*200000000
ab_trans_num_actd = sum(ab_actd[ab_actd$V1!=ab_actd$V4,7])/162823588*200000000
bb_cis_num_actd = sum(bb_actd[bb_actd$V1==bb_actd$V4,7])/162823588*200000000
bb_trans_num_actd = sum(bb_actd[bb_actd$V1!=bb_actd$V4,7])/162823588*200000000

counts = data.frame(BB =c(39.5,38.8),AB=c(20.4,23.2),AA = c(40.1,38))
barplot(as.matrix(counts), main="",
        xlab="", col=c("#2BA809","#F97164"),ylab=('%Interaction'), beside=T,ylim=c(0,50),legend.text =c('Ctrl','ActD') )

counts = data.frame(BB_cis = c(bb_cis_num,bb_cis_num_actd),AB_cis=c(ab_cis_num,ab_cis_num_actd),AA_cis = c(aa_cis_num,aa_cis_num_actd),
                  BB_trans=c(bb_trans_num,bb_trans_num_actd),AB_trans=c(ab_trans_num,ab_trans_num_actd),
                  AA_trans = c(aa_trans_num,aa_trans_num_actd))
barplot(as.matrix(counts), main="",
        xlab="", col=c("#2BA809","#F97164"), beside=T,ylim=c(0,80000000),legend.text =c('Ctrl','ActD') )


```

## Fig 3G and 4B
```{r}
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))
ggplot(data.frame(group = c('AtoB','BtoA'),value=c(0.8,2.8)),aes(x=group,y=value)) +
  geom_col(aes(fill = group),width=0.6) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800", "#FC4E07"))+theme_bw() +
  theme(axis.line = element_line(size=0.5, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank(),
        axis.text.x=element_text(colour="black", size = 9),
        axis.text.y=element_text(colour="black", size = 9))+xlab("")+ylab("% Switched compartment")+ylim(0,3)
pie(c(532/768*100,100-532/768*100), labels = c("hNAD","non-hNAD"), border="white", col=c('#2BA809','#E7B800') )
```

